/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import javax.swing.JOptionPane;


/**
 *
 * @author Brayan
 */
public class Logueo extends javax.swing.JFrame {

    /**
     * Creates new form Logueo
     */
    public Logueo() {
        initComponents();
         setLocationRelativeTo(null);
         jUser.setBackground(new java.awt.Color(0,0,0,1));
         jContra.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jOlvideContra = new javax.swing.JLabel();
        Jnocuenta = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        OjoDisable = new javax.swing.JLabel();
        OjoEnable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jContra = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jbotonclic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(154, 218, 154));
        jPanel1.setForeground(new java.awt.Color(51, 204, 0));
        jPanel1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setText("Bienvenido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jCheckBox1.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jCheckBox1.setText("Recordar");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel4.setText("     X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 48, 39));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel5.setText("Usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 20));

        jOlvideContra.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jOlvideContra.setText("olvidaste tu contraseña?");
        jOlvideContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOlvideContraMouseClicked(evt);
            }
        });
        jPanel1.add(jOlvideContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        Jnocuenta.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        Jnocuenta.setForeground(new java.awt.Color(255, 255, 51));
        Jnocuenta.setText("creala");
        Jnocuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JnocuentaMouseClicked(evt);
            }
        });
        jPanel1.add(Jnocuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-usuario-20.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 90, 60));

        OjoDisable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-invisible-20.png"))); // NOI18N
        OjoDisable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OjoDisableMouseClicked(evt);
            }
        });
        jPanel1.add(OjoDisable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 90, 80));

        OjoEnable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-visible-20.png"))); // NOI18N
        OjoEnable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OjoEnableMouseClicked(evt);
            }
        });
        jPanel1.add(OjoEnable, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 90, 80));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel1.setText("Inicio de sesion ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 300, 50));

        jLabel7.setText("___________________________________________");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 310, 50));

        jUser.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jUser.setBorder(null);
        jUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserActionPerformed(evt);
            }
        });
        jPanel1.add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 300, 50));

        jLabel6.setText("___________________________________________");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 310, 50));

        jContra.setBorder(null);
        jContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContraActionPerformed(evt);
            }
        });
        jPanel1.add(jContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 300, 60));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel10.setText("X");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -10, 90, 60));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel9.setText("¿No tienes cuenta?");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 120, 20));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel12.setText("Ingresar");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jbotonclic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image (1).png"))); // NOI18N
        jbotonclic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbotonclicMouseClicked(evt);
            }
        });
        jPanel1.add(jbotonclic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 330, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 370, 490));

        jPanel2.setBackground(new java.awt.Color(86, 210, 86));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/9628536-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 20, 560, 440));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jContraActionPerformed

    private void jUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserActionPerformed

    private void OjoDisableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OjoDisableMouseClicked
       
        jContra.setEchoChar((char)0);
         OjoDisable.setVisible(false);
        OjoDisable.setEnabled(false);
        OjoEnable.setEnabled(true);
        OjoEnable.setEnabled(true);
        
    }//GEN-LAST:event_OjoDisableMouseClicked

    private void OjoEnableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OjoEnableMouseClicked
       
        
        
        
         jContra.setEchoChar((char)8226);
         OjoDisable.setVisible(true);
        OjoDisable.setEnabled(true);
        OjoEnable.setEnabled(false);
        OjoEnable.setEnabled(false);
        
        
    }//GEN-LAST:event_OjoEnableMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
       for (double i = 0.0; i <= 1.0; i = i + 0.1) { 
    String val = String.valueOf(i);
    float f = Float.valueOf(val);
    this.setOpacity(f);
    try { 
        Thread.sleep(20);
    } catch (Exception e) {
       
    }
}
    }//GEN-LAST:event_formWindowOpened

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void JnocuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JnocuentaMouseClicked
        
      
        
        
         Registro a = new Registro();
    a.setVisible(true);
    this.setVisible(false);
    
    }//GEN-LAST:event_JnocuentaMouseClicked

    private void jbotonclicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbotonclicMouseClicked

          String usuario = jUser.getText();
        String contraseña = new String(jContra.getPassword());

        if (Contraseñas.autenticarUsuario(usuario,contraseña)) {
           
            JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso");
        } else {
       
            JOptionPane.showMessageDialog(this, "Contraseña o usuario incorrecto");
        }
    
    }//GEN-LAST:event_jbotonclicMouseClicked

    private void jOlvideContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOlvideContraMouseClicked
       
        
        
         OlvideContraseña contra = new OlvideContraseña();
    contra.setVisible(true);
    this.setVisible(false);
        
        
        
        
    }//GEN-LAST:event_jOlvideContraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jnocuenta;
    private javax.swing.JLabel OjoDisable;
    private javax.swing.JLabel OjoEnable;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPasswordField jContra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jOlvideContra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jUser;
    private javax.swing.JLabel jbotonclic;
    // End of variables declaration//GEN-END:variables
}
