/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import javax.swing.JOptionPane;

/**
 *
 * @author Brayan
 */
public class OlvideContraseña extends javax.swing.JFrame {

    /**
     * Creates new form OlvideContraseña
     */
    public OlvideContraseña() {
        initComponents();
        setLocationRelativeTo(null);
        jContra.setBackground(new java.awt.Color(0,0,0,1));
         jUser1.setBackground(new java.awt.Color(0,0,0,1));
         jUser2.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jUser1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jUser2 = new javax.swing.JTextField();
        jContra = new javax.swing.JPasswordField();
        OjoDisable = new javax.swing.JLabel();
        OjoEnable = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbotonclic = new javax.swing.JLabel();
        NuevaContra = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        CodigoConfirmacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(154, 218, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel10.setText("X");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 50, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel1.setText("Recuperar contraseña");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 390, 50));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel5.setText("Correo electrónico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 20));

        jLabel7.setText("________________________________________");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 280, 50));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setText("Nueva contraseña");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel8.setText("________________________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 280, 50));

        jUser1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jUser1.setBorder(null);
        jUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUser1ActionPerformed(evt);
            }
        });
        jPanel1.add(jUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 300, 50));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel9.setText("Codigo de confirmacion");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel11.setText("________________________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 280, 50));

        jUser2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jUser2.setBorder(null);
        jUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUser2ActionPerformed(evt);
            }
        });
        jPanel1.add(jUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, 50));

        jContra.setBorder(null);
        jContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContraActionPerformed(evt);
            }
        });
        jPanel1.add(jContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 300, 60));

        OjoDisable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-invisible-20.png"))); // NOI18N
        OjoDisable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OjoDisableMouseClicked(evt);
            }
        });
        jPanel1.add(OjoDisable, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 50, 110));

        OjoEnable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-visible-20.png"))); // NOI18N
        OjoEnable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OjoEnableMouseClicked(evt);
            }
        });
        jPanel1.add(OjoEnable, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 40, 70));

        jPanel2.setBackground(new java.awt.Color(86, 210, 86));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 290, 340));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setText("Cambiar contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 180, -1));

        jbotonclic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image (1).png"))); // NOI18N
        jbotonclic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbotonclicMouseClicked(evt);
            }
        });
        jPanel1.add(jbotonclic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 330, 60));

        NuevaContra.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        NuevaContra.setForeground(new java.awt.Color(255, 0, 204));
        NuevaContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuevaContraMouseClicked(evt);
            }
        });
        jPanel1.add(NuevaContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 320, 20));

        Correo.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Correo.setForeground(new java.awt.Color(255, 0, 204));
        Correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CorreoMouseClicked(evt);
            }
        });
        jPanel1.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 320, 20));

        CodigoConfirmacion.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        CodigoConfirmacion.setForeground(new java.awt.Color(255, 0, 204));
        CodigoConfirmacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodigoConfirmacionMouseClicked(evt);
            }
        });
        jPanel1.add(CodigoConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 320, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:

        System.exit(0);

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUser1ActionPerformed

    private void jUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUser2ActionPerformed

    private void jContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jContraActionPerformed

    private void OjoEnableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OjoEnableMouseClicked

        
         jContra.setEchoChar((char)8226);
         OjoDisable.setVisible(true);
        OjoDisable.setEnabled(true);
        OjoEnable.setEnabled(false);
        OjoEnable.setEnabled(false);

    }//GEN-LAST:event_OjoEnableMouseClicked

    private void OjoDisableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OjoDisableMouseClicked
        
        jContra.setEchoChar((char)0);
         OjoDisable.setVisible(false);
        OjoDisable.setEnabled(false);
        OjoEnable.setEnabled(true);
        OjoEnable.setEnabled(true);
    }//GEN-LAST:event_OjoDisableMouseClicked

    private void jbotonclicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbotonclicMouseClicked
 
     String password = new String(jContra.getPassword());

    if (jUser1.getText().isEmpty()) {
        Correo.setText("Campo Correo no puede estar vacío");
    } else {
        Correo.setText(""); 
    }

    if (jUser2.getText().isEmpty()) {
        CodigoConfirmacion.setText("Campo Código de Confirmación no puede estar vacío");
    } else {
        CodigoConfirmacion.setText(""); 
    }

    
    if (password.length() < 6 || !password.matches(".*[a-zA-Z].*")) {
        NuevaContra.setText("La contraseña debe tener al menos 6 dígitos y contener al menos una letra.");
    } else {
        NuevaContra.setText(""); 
       
        JOptionPane.showMessageDialog(this, "Contraseña cambiada con éxito");
        
     
        this.setVisible(false);

       
        Logueo logueoWindow = new Logueo();

    
        logueoWindow.setVisible(true);
    }


    }//GEN-LAST:event_jbotonclicMouseClicked

    private void NuevaContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuevaContraMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaContraMouseClicked

    private void CorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorreoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoMouseClicked

    private void CodigoConfirmacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodigoConfirmacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoConfirmacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OlvideContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OlvideContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OlvideContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OlvideContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OlvideContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodigoConfirmacion;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel NuevaContra;
    private javax.swing.JLabel OjoDisable;
    private javax.swing.JLabel OjoEnable;
    private javax.swing.JPasswordField jContra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jUser1;
    private javax.swing.JTextField jUser2;
    private javax.swing.JLabel jbotonclic;
    // End of variables declaration//GEN-END:variables
}
