/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Brayan
 */
public class Registro extends javax.swing.JFrame {
private boolean label4MousePressed = false;
    /**
     * Creates new form Registro
     */
    public Registro() {
        
        initComponents();
        
        setLocationRelativeTo(null);
        jUser.setBackground(new java.awt.Color(0,0,0,1));
        jmail.setBackground(new java.awt.Color(0,0,0,1));
        jcontra.setBackground(new java.awt.Color(0,0,0,1));
        jcontra2.setBackground(new java.awt.Color(0,0,0,1));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jUser = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcontra = new javax.swing.JPasswordField();
        jcontra2 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        OjoDisable2 = new javax.swing.JLabel();
        OjoEnable2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        OjoDisable3 = new javax.swing.JLabel();
        OjoEnable3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noCorreo = new javax.swing.JLabel();
        Caracteres = new javax.swing.JLabel();
        noCoinciden1 = new javax.swing.JLabel();
        noUser = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jbotonclic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(154, 218, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel1.setText("Registro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 50));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel5.setText("Correo electrónico");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jLabel8.setText("_____________________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, 50));

        jLabel7.setText("_____________________________________");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 260, 50));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setText("Repetir contraseña");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 20));

        jUser.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jUser.setBorder(null);
        jUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserActionPerformed(evt);
            }
        });
        jPanel1.add(jUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 320, 50));

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel9.setText("Usuario");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jmail.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jmail.setBorder(null);
        jmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmailActionPerformed(evt);
            }
        });
        jPanel1.add(jmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 320, 50));

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel10.setText("Contraseña");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        jLabel11.setText("_____________________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 260, 50));

        jcontra.setBorder(null);
        jcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcontraActionPerformed(evt);
            }
        });
        jPanel1.add(jcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, 50));

        jcontra2.setBorder(null);
        jcontra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcontra2ActionPerformed(evt);
            }
        });
        jPanel1.add(jcontra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 240, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-usuario-20.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 70, 60));

        OjoDisable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-invisible-20.png"))); // NOI18N
        OjoDisable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OjoDisable2MouseClicked(evt);
            }
        });
        jPanel1.add(OjoDisable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 80, 50));

        OjoEnable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-visible-20.png"))); // NOI18N
        OjoEnable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OjoEnable2MouseClicked(evt);
            }
        });
        jPanel1.add(OjoEnable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 80, 50));

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 51));
        jLabel13.setText("Ingresar");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-correo-20.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 50, 60));

        jLabel12.setText("_____________________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, 50));

        OjoDisable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-invisible-20.png"))); // NOI18N
        OjoDisable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OjoDisable3MouseClicked(evt);
            }
        });
        jPanel1.add(OjoDisable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 80, 50));

        OjoEnable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-visible-20.png"))); // NOI18N
        OjoEnable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OjoEnable3MouseClicked(evt);
            }
        });
        jPanel1.add(OjoEnable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 80, 50));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 60, 40));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        jLabel3.setText("¿Ya tiene una cuenta?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        noCorreo.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        noCorreo.setForeground(new java.awt.Color(255, 0, 204));
        noCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noCorreoMouseClicked(evt);
            }
        });
        jPanel1.add(noCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 230, 20));

        Caracteres.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        Caracteres.setForeground(new java.awt.Color(255, 0, 204));
        Caracteres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CaracteresMouseClicked(evt);
            }
        });
        jPanel1.add(Caracteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 320, 20));

        noCoinciden1.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        noCoinciden1.setForeground(new java.awt.Color(255, 0, 204));
        noCoinciden1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noCoinciden1MouseClicked(evt);
            }
        });
        jPanel1.add(noCoinciden1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 230, 20));

        noUser.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        noUser.setForeground(new java.awt.Color(255, 0, 204));
        noUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noUserMouseClicked(evt);
            }
        });
        jPanel1.add(noUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 230, 20));

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel17.setText("Crear");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jbotonclic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/image (1).png"))); // NOI18N
        jbotonclic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbotonclicMouseClicked(evt);
            }
        });
        jPanel1.add(jbotonclic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 330, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 480));

        jPanel2.setBackground(new java.awt.Color(86, 210, 86));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/9628536-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 560, 440));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 410, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserActionPerformed

    private void jmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmailActionPerformed

    private void OjoDisable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OjoDisable2MouseClicked
    
        jcontra2.setEchoChar((char)0);
         OjoDisable2.setVisible(false);
        OjoDisable2.setEnabled(false);
        OjoEnable2.setEnabled(true);
        OjoEnable2.setEnabled(true);
        
    }//GEN-LAST:event_OjoDisable2MouseClicked

    private void OjoEnable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OjoEnable2MouseClicked
       
        
        jcontra2.setEchoChar((char)8226);
         OjoDisable2.setVisible(true);
        OjoDisable2.setEnabled(true);
        OjoEnable2.setEnabled(false);
        OjoEnable2.setEnabled(false);
    }//GEN-LAST:event_OjoEnable2MouseClicked

    private void jcontra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcontra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcontra2ActionPerformed

    private void jcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcontraActionPerformed

    private void OjoDisable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OjoDisable3MouseClicked
  jcontra.setEchoChar((char)0);
         OjoDisable3.setVisible(false);
        OjoDisable3.setEnabled(false);
        OjoEnable3.setEnabled(true);
        OjoEnable3.setEnabled(true);       
    }//GEN-LAST:event_OjoDisable3MouseClicked

    private void OjoEnable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OjoEnable3MouseClicked
        
        jcontra.setEchoChar((char)8226);
         OjoDisable3.setVisible(true);
        OjoDisable3.setEnabled(true);
        OjoEnable3.setEnabled(false);
        OjoEnable3.setEnabled(false);
    }//GEN-LAST:event_OjoEnable3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        System.exit(0);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
       
         Logueo a = new Logueo ();
    a.setVisible(true);
    this.setVisible(false);
        
        
    }//GEN-LAST:event_jLabel13MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      for (double i = 0.0; i <= 1.0; i = i + 0.1) { 
    String val = String.valueOf(i);
    float f = Float.valueOf(val);
    this.setOpacity(f);
    try { 
        Thread.sleep(20);
    } catch (Exception e) {
       
    }
}
    }//GEN-LAST:event_formWindowActivated

    private void noCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noCorreoMouseClicked
      
    }//GEN-LAST:event_noCorreoMouseClicked

    private void CaracteresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaracteresMouseClicked
       
    }//GEN-LAST:event_CaracteresMouseClicked

    private void noCoinciden1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noCoinciden1MouseClicked
      
    }//GEN-LAST:event_noCoinciden1MouseClicked

    private void noUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noUserMouseClicked
      
    }//GEN-LAST:event_noUserMouseClicked

    private void jbotonclicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbotonclicMouseClicked

           String mensajeCorreo = "";
        String mensajeContrasena = "";
        String mensajeUsuario = "";

        String usuario = jUser.getText();
        String correo = jmail.getText();
        String contrasena = new String(jcontra.getPassword());
        String contrasenaRepetida = new String(jcontra2.getPassword());

        if (usuario.isEmpty()) {
            mensajeUsuario = "El campo de usuario no puede estar vacío.";
        }

        if (correo.isEmpty()) {
            mensajeCorreo = "El campo de correo no puede estar vacío.";
        }

        if (contrasena.isEmpty()) {
            mensajeContrasena = "El campo de contraseña no puede estar vacío.";
        }

        if (!correo.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$")) {
            mensajeCorreo = "Correo no válido";
        }

        if (contrasena.length() < 6) {
            mensajeContrasena = "La contraseña debe tener al menos 6 caracteres.";
        } else if (!contrasena.matches(".*\\d.*")) {
            mensajeContrasena = "La contraseña debe contener al menos un número.";
        } else if (contrasena.matches(".*\\W.*")) {
            mensajeContrasena = "La contraseña no debe contener signos.";
        }

        if (!contrasena.equals(contrasenaRepetida)) {
            mensajeContrasena = "Las contraseñas no coinciden.";
        }

        noCorreo.setText(mensajeCorreo);
        Caracteres.setText(mensajeContrasena);
        noUser.setText(mensajeUsuario);

        if (mensajeCorreo.isEmpty() && mensajeContrasena.isEmpty() && mensajeUsuario.isEmpty()) {
           
            try {
                BufferedWriter writer = new BufferedWriter(new FileWriter("usuarios.txt", true));
                writer.write(usuario + "," + correo + "," + contrasena);
                writer.newLine();
                writer.close();
            } catch (IOException e) {
                e.printStackTrace();
            }

            JOptionPane.showMessageDialog(this, "¡Registro exitoso!", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            Logueo login = new Logueo();
            login.setVisible(true);
            this.dispose();
        }
    

    }//GEN-LAST:event_jbotonclicMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Caracteres;
    private javax.swing.JLabel OjoDisable2;
    private javax.swing.JLabel OjoDisable3;
    private javax.swing.JLabel OjoEnable2;
    private javax.swing.JLabel OjoEnable3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jUser;
    private javax.swing.JLabel jbotonclic;
    private javax.swing.JPasswordField jcontra;
    private javax.swing.JPasswordField jcontra2;
    private javax.swing.JTextField jmail;
    private javax.swing.JLabel noCoinciden1;
    private javax.swing.JLabel noCorreo;
    private javax.swing.JLabel noUser;
    // End of variables declaration//GEN-END:variables
}
